### ISSUE TITLE
Styling of the application 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/node_app#2]
Internal pages do not have appropriate  alignments , styles etc  would like the application to look better and more pleasing .

**Comment by yanmarex** [comment]
Hi! I going to take this Issue.

**Comment by DiptoChakrabarty** [comment]
> Hi! I going to take this Issue.

great @yanmarex  please go ahead

**Comment by DEVANG2502** [comment]
hello!can i wrok on this issue?

**Comment by DiptoChakrabarty** [comment]
It has been done already by @yanmarex
